version: '3.8'

services:
  client:
    build:
      context: ../apps/client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ../apps/client:/app
      - /app/node_modules

  server:
    build:
      context: ../apps/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://uci:ucipass@postgres:5432/uci_chat
    volumes:
      - ../apps/server:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    environment: 
      POSTGRES_USER: uci
      POSTGRES_PASSWORD: ucipass
      POSTGRES_DB: uci_chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

volumes:
  postgres_data:
