name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Dependencies (Shared)
        working-directory: packages/shared-types
        run: npm install
      
      - name: Install Dependencies (Client)
        working-directory: apps/client
        run: npm install
      
      - name: Install Dependencies (Server)
        working-directory: apps/server
        run: npm install
      
      - name: Build Shared Types
        working-directory: packages/shared-types
        run: npm run build
      
      - name: Build Client
        working-directory: apps/client
        run: npm run build
      
      - name: Build Server
        working-directory: apps/server
        run: npm run build
