name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js (Shared)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/shared-types/package-lock.json
      
      - name: Setup Node.js (Client)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/client/package-lock.json
      
      - name: Setup Node.js (Server)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/server/package-lock.json
      
      - name: Install Dependencies (Shared)
        working-directory: packages/shared-types
        run: npm ci
      
      - name: Install Dependencies (Client)
        working-directory: apps/client
        run: npm ci
      
      - name: Install Dependencies (Server)
        working-directory: apps/server
        run: npm ci
      
      - name: Build Shared Types
        working-directory: packages/shared-types
        run: npm run build
      
      - name: Build Client
        working-directory: apps/client
        run: npm run build
      
      - name: Build Server
        working-directory: apps/server
        run: npm run build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          # Build and push client image
          docker build -t ghcr.io/${{ github.repository }}/client:latest ./apps/client
          docker push ghcr.io/${{ github.repository }}/client:latest
          
          # Build and push server image
          docker build -t ghcr.io/${{ github.repository }}/server:latest ./apps/server
          docker push ghcr.io/${{ github.repository }}/server:latest
