name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js (Shared)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/shared-types/package-lock.json
      
      - name: Setup Node.js (Client)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/client/package-lock.json
      
      - name: Setup Node.js (Server)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/server/package-lock.json
      
      - name: Install Dependencies (Shared)
        working-directory: packages/shared-types
        run: npm ci
      
      - name: Install Dependencies (Client)
        working-directory: apps/client
        run: npm ci
      
      - name: Install Dependencies (Server)
        working-directory: apps/server
        run: npm ci
      
      - name: Build Shared Types
        working-directory: packages/shared-types
        run: npm run build
      
      - name: Build Client
        working-directory: apps/client
        run: npm run build
      
      - name: Build Server
        working-directory: apps/server
        run: npm run build
